### ISSUE TITLE
styling problems

### ISSUE THREAD

**Issue by xavier290** [xavier290/Coderhub#4]
@theotrg07  we have some problems with the way you wrote some html in js, which led to the following error:

![Screenshot (277)](https://user-images.githubusercontent.com/63680686/132582160-708cf57f-fafa-4da3-ad09-89dfaddb77d5.png)

the way to solve this would be to put the "a" tag inside the button and not the other way around as it is right now, it's a minor mistake so it will be really easy to fix

**Comment by theotrg07** [comment]
ok i have fixed it and pull requested as well

**Comment by xavier290** [comment]
@theotrg07 okay perfect let me look it up
